{% set name = "numba-cuda" %}
{% set version = "0.15.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/numba_cuda-{{ version }}.tar.gz
  sha256: a5bca48ace64a9456cf8a9c3dadddda23766cdd04276e2ab002a4c623506b8b2

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<39]

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    - numba >=0.59.1

test:
  imports:
    - numba_cuda
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NVIDIA/numba-cuda
  summary: CUDA target for Numba
  description: |
    A Numba target for compiling Python code to excute on CUDA GPUs.
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  doc_url: https://nvidia.github.io/numba-cuda
  dev_url: https://github.com/NVIDIA/numba-cuda

extra:
  recipe-maintainers:
    - cbouss
