{% set name = "numba-cuda" %}
{% set version = "0.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1dbd58f4af25c984c067437872b211c7b7091807fa76fae1d37b41d982ae3d2e

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<39]
  skip: true  # [osx]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - numpy {{ numpy }}
  run:
    - python
    - packaging
    - numpy >=1.22
    - numba >=0.60.0
    - cuda-bindings >=12.9.1,<14.0.0
    - cuda-core >=0.5.1,<1.0.0
    # Please see PKG-9812 for discussion about the CUDA dependencies.
    - cuda-version >=12
    - cuda-nvcc-impl
    - cuda-cudart-dev

test:
  requires:
    - pip
  imports:
    - numba_cuda
  commands:
    - pip check

about:
  home: https://github.com/NVIDIA/numba-cuda
  summary: A CUDA target for Numba
  description: |
    A Numba target for compiling Python code to excute on CUDA GPUs.
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  doc_url: https://nvidia.github.io/numba-cuda
  dev_url: https://github.com/NVIDIA/numba-cuda

extra:
  recipe-maintainers:
    - cbouss
