{% set name = "numba-cuda" %}
{% set version = "0.22.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 8688dd21120ab326c703a1319296a5d889f7db3f17a45e5ac9e22126bb359191

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<39]
  skip: true  # [osx]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - numpy >=2.1.0
  run:
    - python
    - numpy >=1.22
    - numba >=0.60.0
    - cuda-bindings >=12.9.1,<14.0.0
    - cuda-core >=0.3.2,<1.0.0
    - cuda-version >=12
    - cuda-nvcc-impl
    - cuda-cudart-dev
    # - cuda-nvrtc
    # - libnvjitlink
    # - cuda-cccl
    # - cuda-nvvm

test:
  requires:
    - pip
  imports:
    - numba_cuda
  commands:
    - pip check

about:
  home: https://github.com/NVIDIA/numba-cuda
  summary: A CUDA target for Numba
  description: |
    A Numba target for compiling Python code to excute on CUDA GPUs.
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  doc_url: https://nvidia.github.io/numba-cuda
  dev_url: https://github.com/NVIDIA/numba-cuda

extra:
  recipe-maintainers:
    - cbouss
