context:
  name: numba-cuda
  sdist_name: numba_cuda
  version: "0.0.18"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ sdist_name }}-${{ version }}.tar.gz
  sha256: a7ca2f4d7d73d8d100da82e90d59ed89e61a25858a3a544ace123a20cb50b750

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - numba >=0.59.1

tests:
  - python:
      imports:
      - numba_cuda
      pip_check: true

about:
  homepage: https://github.com/NVIDIA/numba-cuda
  summary: 'A CUDA target for Numba'
  description: |
    A Numba target for compiling Python code to excute on CUDA GPUs.
  license: BSD-2-Clause
  license_file: LICENSE
  documentation: https://nvidia.github.io/numba-cuda
  repository: https://github.com/NVIDIA/numba-cuda

extra:
  recipe-maintainers:
    - gmarkall
